// Generated by gencpp from file aeriaman/AddTwoInts.msg
// DO NOT EDIT!


#ifndef AERIAMAN_MESSAGE_ADDTWOINTS_H
#define AERIAMAN_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <aeriaman/AddTwoIntsRequest.h>
#include <aeriaman/AddTwoIntsResponse.h>


namespace aeriaman
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace aeriaman


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aeriaman::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::aeriaman::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::aeriaman::AddTwoInts > {
  static const char* value()
  {
    return "aeriaman/AddTwoInts";
  }

  static const char* value(const ::aeriaman::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::aeriaman::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::aeriaman::AddTwoInts > 
template<>
struct MD5Sum< ::aeriaman::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aeriaman::AddTwoInts >::value();
  }
  static const char* value(const ::aeriaman::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aeriaman::AddTwoIntsRequest> should match 
// service_traits::DataType< ::aeriaman::AddTwoInts > 
template<>
struct DataType< ::aeriaman::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::aeriaman::AddTwoInts >::value();
  }
  static const char* value(const ::aeriaman::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aeriaman::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::aeriaman::AddTwoInts > 
template<>
struct MD5Sum< ::aeriaman::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aeriaman::AddTwoInts >::value();
  }
  static const char* value(const ::aeriaman::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aeriaman::AddTwoIntsResponse> should match 
// service_traits::DataType< ::aeriaman::AddTwoInts > 
template<>
struct DataType< ::aeriaman::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::aeriaman::AddTwoInts >::value();
  }
  static const char* value(const ::aeriaman::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AERIAMAN_MESSAGE_ADDTWOINTS_H
